
export let table = {
  tableName: 'examrecord',
  comments: '心理记录',
}

export let columns = [
  {
    columnName: 'username',
    comments: '用户名',
    form_type: 'YyText',
  },
  {
    columnName: 'paperid',
    comments: '试卷名称',
    form_type: 'YyExamPaperid',
    hiden: '2,3',
    isNullable: '否',
  },
  {
    columnName: 'papername',
    comments: '试卷名称',
    form_type: 'YyText',
    hiden: '6',
    form_hidden: true,
  },
  {
    columnName: 'questionid',
    comments: '试题id',
    hiden: '2,3,4,6,7',
    form_type: 'YyText',
  },
  {
    columnName: 'questionname',
    comments: '试题名称',
    form_type: 'YyQuill',
    table_type: 'TableHtml',
  },    
  {
    columnName: 'type',
    comments: '类型',
    form_type: 'YyExamType',
    table_type: 'TableTag',
    isNullable: '否',  
    options: [
      {
        value: 0,
        label: '客观题',
        type: 'primary',
        option_hidden: false,
      },
      {
        value: 1,       
        label: '多选题',
        type: 'success',
        option_hidden: true,
      },
      {
        value: 2,
        label: '判断题',
        type: 'info',
        option_hidden: true,
      },
      {
        value: 3,
        label: '填空题',
        type: 'warning',
        option_hidden: true,       
      },
      {
        value: 4,
        label: '主观题',
        type: 'danger',
        option_hidden: false,
      }  
    ],   
  }, 
  {
    columnName: 'ismark',
    comments: '是否批卷',
    hiden: '2,3,4,6,7',
    form_type: 'YyText',
  },
  {
    columnName: 'options',
    comments: '选项',
    form_type: 'YyExamOption',
    table_type: 'TableExamOption',
    form_hidden: false,
  },     
  {
    columnName: 'score',
    comments: '分值',
    form_type: 'YyTextNumber',
    hiden: '2,3,4',
    form_hidden: true, 
  },
  {
    columnName: 'answer',
    comments: '正确答案',
    form_type: 'YySingleSelect',
    hiden: '2,3,4',
    form_hidden: true,      
    options: [],
  },
  {
    columnName: 'analysis',
    comments: '答案解析',
    form_type: 'YyQuill',
    table_type: 'TableHtml',
  },
  {
    columnName: 'myscore',
    comments: '试题得分',
    form_type: 'YyTextNumber',
    isNullable: '否',
  },
  {
    columnName: 'myanswer',    
    comments: '考生答案',
    form_type: 'YyText',
  },
  {
    columnName: 'examno',
    comments: '考试编号',
    hiden: '2,3,4,6,7',
    form_type: 'YyText',
  },
  {
    columnName: 'userid',
    comments: '用户id',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '长',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },   
  {
    columnName: 'addtime',    
    comments: '考试时间',
    form_type: 'YyText',
  },  
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'papername',
    comments: '试卷名称',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '试卷名称',
    form_type: 'YyText', 
    options: [],
  },
  {
    queryFlagInput: ['是'],
    columnName: 'questionname',
    comments: '试题名称',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '试题名称',
    form_type: 'YyText', 
    options: [],
  },
]

export let headerButtons = []
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },  
]