export let table = {
  tableName: 'xinqingriji',
  comment: '',
  comments: '心情日记',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '是',
  foreEndList: '否',
  foreEndAdd: '否',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  tplist: '是',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '是',
  discuss: '是',
  storeUp: '是',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: 'yonghu',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '否',
  frontRegister: '否',
  backLogin: '否',
  backRegister: '否',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '是',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '轮播图/心理健康',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: 'fabushijian',
  sortOrder: 'desc',
  titleName: 'rijibiaoti',
  couponType: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
}


export let columns = [
  {
    columnName: 'rijibiaoti',
    comments: '日记标题',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'rijineirong',
    comments: '日记内容',
    type: '多',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    form_type: 'YyTextArea',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'rijitupian',
    comments: '日记图片',
    type: '图',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    table_type: 'TableImage',
    form_type: 'YyFile',
    form_accept: 'image/*',
    formMaxCount: 3,
    imageRecognize: false, 
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'fabushijian',
    comments: '发布时间',
    type: '日长',
    dateCurFlag: '是',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '降',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyDatePicker',
    form_showTime: true,
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yonghuzhanghao',
    comments: '用户账号',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: 'yonghu',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '是',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yonghuxingming',
    comments: '用户姓名',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '是',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '0',
    table_type: 'TableMaskName',
    isMask: true,
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'thumbsupnum',
    comments: '赞',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'crazilynum',
    comments: '踩',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'discussnum',
    comments: '评论数',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '是',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'storeupnum',
    comments: '收藏数',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '数',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '0',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyTextNumber',  
    form_hidden: false,    
    options: [],
  },
]

export let searchColumns = [
  {
    queryFlagInput: ['是'],
    columnName: 'rijibiaoti',
    comments: '日记标题',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '日记标题',
    form_type: 'YyText', 
    options: [],
  },
  {
    queryFlagInput: ['是'],
    columnName: 'fabushijianstart',
    comments: '发布时间起',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '发布时间起',
    form_type: 'YyDatePicker',
    form_showTime: true,
    isRangeSearch: true,
    options: [],
  },
  {
    queryFlagInput: ['是'],
    columnName: 'fabushijianend',
    comments: '发布时间止',
    level: 0,
    refTable: '',
    refColumn: '',
    placeholder: '发布时间止',
    form_type: 'YyDatePicker',
    form_showTime: true,
    isRangeSearch: true,
    options: [],
  },
]
export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
]
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
  {
    title: '修改', 
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },

  {
    title: '查看评论',
    name: '查看评论',
    key: 'discuss',
    iconName: 'ChatLineSquare',
  },
]

/**
 * @description 用权
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}