export let table = {
  tableName: 'jiankangyujing',
  comment: '',
  comments: '健康预警',
  sfsh: '否',
  authPeople: '否',
  emailRegister: '否',
  detail: '是',
  foreEndList: '是',
  foreEndAdd: '是',
  jifen: '否',
  isReverse: '否',
  hasCart: '否',
  limit: '否',
  mulGraphType: '',
  virtualPay: '否',
  hasSales: false,
  vip: '否',
  groupBuy: '否',
  creditScore: '否',
  authSeparate: '否',
  tplist: '是',
  addHomePage: '否',
  hasPay: '否',
  hasAlipay: '否',
  hasRegister: '否',
  thumbsUp: '否',
  discuss: '否',
  storeUp: '否',
  statistics: '',
  mulStatistics: '',
  selectSeat: '否',
  menuJump: '列表',
  browseClick: '否',
  browseHistory: '否',
  foreEndListAuth: '否',
  location: '否',
  isAdmin: '否',
  sessionReadTable: '',
  merchantRole: '',
  exportExcel: '否',
  importExcel: '否',
  hasPrint: '否',
  frontLogin: '否',
  frontRegister: '否',
  backLogin: '否',
  backRegister: '否',
  homeSearch: '否',
  mapType: '无',
  homeStatistic: '无',
  passwordProtected: '否',
  tabBar: '否',
  hasChapter: '无',
  hasAuction: '否',
  hasHot: '无',
  hasMusic: '否',
  sharePlatform: '',
  hasChat: '无',
  collaborativeAction: '',
  fkMainTable: '',
  fixedAuth: '',
  passwordWrongNum: '0',
  buttons: '',
  imagePath: '轮播图/心理健康',
  orderNum: '',
  status: '',
  conflictType: '',
  sortName: '',
  sortOrder: 'desc',
  titleName: 'yonghuxingming',
  couponType: '',

  crossOptTableName: [],
  crossOptButton: [],
  crossOptAudit: [],
  crossOptPay: [],
  crossOptButtonStatusColumns: [],
  crossOptButtonTips: [],

  csuOperateList: [],
  csuTypeList: [],
  csuUpdateTableList: [],
  csuUpdateColumnList: [],
  csuUpdateColumnTypeList: [],
  csuUpdateColumnValueList: [],
  csuMessageList: [],
  csuConditionColumnList_1: [],  
  csuConditionColumnList_2: [],
}


export let columns = [
  {
    columnName: 'yonghuzhanghao',
    comments: '用户账号',
    type: '下2',
    dateCurFlag: '',
    refTable: 'yonghu',
    refColumn: 'yonghuzhanghao',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: 'yonghu',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    form_type: 'YySingleSelectFollow',
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yonghuxingming',
    comments: '用户姓名',
    type: '随',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yujingtixing',
    comments: '预警提醒',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    table_type: 'TableRiskLevel',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'xinlijianyi',
    comments: '心理建议',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyText',  
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'yujingshijian',
    comments: '预警时间',
    type: '日长',
    dateCurFlag: '是',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '',
    form_type: 'YyDatePicker',
    form_showTime: true,
    form_hidden: false,    
    options: [],
  },
  {
    columnName: 'chulizhuangtai',
    comments: '处理状态',
    type: '普',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    table_type: 'TableStatusToggle',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '未处理',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '未处理',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '16',
    form_type: 'YySingleSelect',
    form_hidden: false,
    options: [
      { value: '未处理', label: '未处理', type: 'warning' },
      { value: '已处理', label: '已处理', type: 'success' },
    ],
  },
  {
    columnName: 'chuliyijian',
    comments: '处理意见',
    type: '多',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '128',
    table_type: 'TableOpinion',
    form_type: 'YyTextArea',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'fuzeyishenggonghao',
    comments: '负责医生工号',
    type: '随',
    dateCurFlag: '',
    refTable: 'xinliyisheng',
    refColumn: 'yishenggonghao',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
  {
    columnName: 'fuzeyishengxingming',
    comments: '负责医生姓名',
    type: '随',
    dateCurFlag: '',
    refTable: '',
    refColumn: '',
    refConditionColumn: '',
    refConditionValue: '',
    refConditionQueryMethod: '',
    customize: '',
    authTable: '',
    tplist: '是',
    level: 0,
    isNullable: '',
    isReadonlyInput: [],
    defaultValue: '',
    unique: '',
    loginUser: '',
    formatValidation: '',
    sort: '',
    sessionRead: '',
    sessionColumn: '',
    compare: '',
    alipayColumn: '',
    crossCal: '无',
    examName: '',
    minLength: '',
    maxLength: '',
    faceMatch: '',
    hiden: '',
    encryption: '',
    courseFlag: '',
    columnDefault: '',
    remind: '',
    remindStart: '',
    remindEnd: '',
    remindInput: '',
    colLength: '32',
    form_type: 'YyText',
    form_hidden: false,
    options: [],
  },
]

export let searchColumns = [
]
export let headerButtons = [
  {
    title: '新增',
    name: '新增',
    key: 'add',
    iconName: 'Plus',
    className: 'action-add',
  },
  {
    title: '删除',
    name: '删除',
    key: 'removes',
    iconName: 'Delete',
    className: 'action-removes',
  },
]
export let tableButtons = [
  {
    title: '查看',
    name: '查看',
    key: 'view',
    iconName: 'View',
    className: 'action-view',
  },
  {
    title: '指派/改派医生',
    name: '指派医生',
    key: 'assign',
    iconName: 'User',
    className: 'action-assign',
    isPublic: true,
  },
  {
    title: '删除',
    name: '删除',
    key: 'remove',
    className: 'action-delete',
    iconName: 'Delete',
  },
  {
    title: '修改', 
    name: '修改',
    key: 'edit',
    className: 'action-edit',
    iconName: 'Edit',
  },

]

/**
 * @description 用权
 * titleNames: 标题
 * subTitleNames: 副标题
 * searchNames: 用权。显示的时候，根据这个条件过滤
 */ 
export let timeTable = {
  titleNames: [],
  subTitleNames: [],
  searchNames: []
}