# Generated by Django 2.0 on 2026-08-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config_discussxinlizhishi_discussxinqingriji_doctoradvice_exampaper_examquestion_examrecord_jiankang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '心灵资讯', 'verbose_name_plural': '心灵资讯'},
        ),
        migrations.AddField(
            model_name='jiankangyujing',
            name='chulizhuangtai',
            field=models.CharField(default='未处理', max_length=32, null=True, verbose_name='处理状态'),
        ),
    ]
