# Generated by Django 2.0 on 2026-08-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_jiankangyujing_fuzeyisheng'),
    ]

    operations = [
        migrations.AddField(
            model_name='xinliyisheng',
            name='sfsh',
            field=models.CharField(default='待审核', max_length=255, null=True, verbose_name='是否审核'),
        ),
        migrations.AddField(
            model_name='xinliyisheng',
            name='shhf',
            field=models.TextField(null=True, verbose_name='审核回复'),
        ),
    ]
