# Generated by Django 2.0 on 2026-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20260827_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiankangyujing',
            name='chuliyijian',
            field=models.TextField(null=True, verbose_name='处理意见'),
        ),
    ]
