# Generated by Django 2.0 on 2026-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jiankangyujing_chuliyijian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonghu',
            name='shouji',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='手机'),
        ),
    ]
